version: "3"
services:
  healthfull:
    build: .
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - /opt/app/node_modules # See https://stackoverflow.com/a/32785014 for more
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development